# TODO: How to build images before running the services?
#https://docs.docker.com/reference/compose-file/build/

services:
  vllm-server:
    build: deepseek/
    container_name: vllm-deepseek-server
    image: vllm-deepseek-server:latest
    #restart: always
    #command: "--runtime nvidia --gpus all --ipc=host"
    deploy:                                                         # see https://docs.docker.com/compose/how-tos/gpu-support/
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              #device_ids: ['0', '3']
              capabilities: [gpu]
    ipc: host
    ports:
      - 8000:8000
    volumes:
      - /home/kkobuszewski/projects/LMMs:/root/.cache/huggingface
    #environment:
    #  - OPENAI_API_KEY=/run/secrets/vllm_api_key
    #secrets:
    #  - vllm_api_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  vllm-client:
    build: .
    container_name: vllm-client
    image: vllm-client
    #restart: always
    ports:
      - 8080:8050
    develop:
      watch:
        - action: sync
          path: .
          target: /code
    depends_on:
      vllm-server:
        condition: service_healthy

# see https://docs.docker.com/compose/how-tos/use-secrets/
#secrets:
#  vllm_api_key:
#    file: vllm_api_key.txt
